const styles = {
  page: {
    minHeight: "100vh",
    background: "#F0F4F8",
    fontFamily: "'DM Sans', sans-serif",
  },
  main: {
    maxWidth: 900,
    margin: "0 auto",
    padding: "36px 24px 60px",
  },
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 28,
    flexWrap: "wrap",
    gap: 16,
  },
  title: {
    fontFamily: "'Sora', sans-serif",
    fontSize: 26,
    fontWeight: 700,
    color: "#0F172A",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: "#64748B",
  },
  uploadBtn: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "linear-gradient(135deg, #1D4ED8, #0EA5E9)",
    color: "#fff",
    border: "none",
    padding: "11px 20px",
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    transition: "transform 0.15s",
    boxShadow: "0 4px 12px rgba(29,78,216,0.3)",
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 14,
    marginBottom: 24,
  },
  statCard: {
    background: "#fff",
    borderRadius: 14,
    padding: "18px 20px",
    borderTop: "3px solid",
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
  },
  statTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  statIcon: { fontSize: 18 },
  statNum: {
    fontSize: 28,
    fontWeight: 700,
    fontFamily: "'Sora', sans-serif",
  },
  statLabel: {
    fontSize: 13,
    color: "#64748B",
    fontWeight: 500,
    margin: 0,
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
    flexWrap: "wrap",
    gap: 12,
  },
  filterGroup: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  chip: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "7px 14px",
    borderRadius: 20,
    borderWidth: "1.5px",
    borderStyle: "solid",
    borderColor: "#E2E8F0",
    background: "#fff",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    color: "#475569",
    fontFamily: "inherit",
    transition: "all 0.15s",
  },
  chipActive: {
    background: "#1D4ED8",
    borderColor: "#1D4ED8",
    color: "#fff",
  },
  chipCount: {
    background: "#E2E8F0",
    color: "#475569",
    borderRadius: 10,
    padding: "1px 7px",
    fontSize: 11,
    fontWeight: 600,
  },
  chipCountActive: {
    background: "rgba(255,255,255,0.25)",
    color: "#fff",
  },
  searchWrap: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  searchIcon: {
    position: "absolute",
    left: 12,
    pointerEvents: "none",
  },
  searchInput: {
    padding: "9px 14px 9px 36px",
    borderWidth: "1.5px",
    borderStyle: "solid",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    fontSize: 14,
    fontFamily: "'DM Sans', sans-serif",
    background: "#fff",
    outline: "none",
    width: 220,
    transition: "border-color 0.2s",
    color: "#0F172A",
  },
  errorBox: {
    background: "#FEF2F2",
    border: "1px solid #FECACA",
    borderRadius: 10,
    padding: "14px 18px",
    color: "#DC2626",
    fontSize: 14,
    marginBottom: 16,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  retryBtn: {
    background: "#DC2626",
    color: "#fff",
    border: "none",
    padding: "6px 14px",
    borderRadius: 7,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  loadingWrap: { display: "flex", flexDirection: "column", gap: 12 },
  skeleton: {
    height: 80,
    borderRadius: 14,
    background: "linear-gradient(90deg, #E2E8F0 25%, #F1F5F9 50%, #E2E8F0 75%)",
    backgroundSize: "400px 100%",
    animation: "shimmer 1.4s infinite",
  },
  emptyState: {
    textAlign: "center",
    padding: "60px 20px",
  },
  emptyIcon: { fontSize: 48, marginBottom: 16 },
  emptyTitle: {
    fontFamily: "'Sora', sans-serif",
    fontSize: 18,
    fontWeight: 600,
    color: "#0F172A",
    marginBottom: 8,
  },
  emptyDesc: {
    fontSize: 14,
    color: "#64748B",
    marginBottom: 20,
  },
  emptyBtn: {
    background: "#1D4ED8",
    color: "#fff",
    border: "none",
    padding: "10px 22px",
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
};
export default styles;
