const styles = {
  container: {
    display: "flex",
    minHeight: "100vh",
    fontFamily: "'DM Sans', sans-serif",
  },
  leftPanel: {
    flex: 1,
    background:
      "linear-gradient(145deg, #0F172A 0%, #1E3A5F 60%, #0C4A6E 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "60px 56px",
    position: "relative",
    overflow: "hidden",
  },
  leftContent: {
    position: "relative",
    zIndex: 1,
    maxWidth: 450,
    animation: "fadeIn 0.6s ease",
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 48,
  },
  logoIcon: {
    fontSize: 32,
    filter: "drop-shadow(0 2px 8px rgba(255,255,255,0.1))",
  },
  logoText: {
    color: "#fff",
    fontFamily: "'Sora', sans-serif",
    fontSize: 22,
    fontWeight: 700,
    letterSpacing: "-0.5px",
  },
  heroTitle: {
    fontFamily: "'Sora', sans-serif",
    fontSize: 44,
    fontWeight: 800,
    color: "#fff",
    lineHeight: 1.15,
    letterSpacing: "-1.5px",
    marginBottom: 20,
  },
  heroDesc: {
    fontSize: 16,
    color: "#94A3B8",
    lineHeight: 1.7,
    marginBottom: 40,
  },
  features: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  feature: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    color: "#E2E8F0",
    fontSize: 15,
  },
  featureIcon: {
    width: 24,
    height: 24,
    background: "rgba(14,165,233,0.15)",
    border: "1px solid rgba(14,165,233,0.3)",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    fontWeight: 700,
    color: "#38BDF8",
  },
  rightPanel: {
    width: 500,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#F8FAFC",
    padding: "40px",
  },
  formCard: {
    width: "100%",
    maxWidth: 400,
    animation: "fadeIn 0.5s ease 0.2s both",
  },
  formHeader: {
    marginBottom: 32,
  },
  formTitle: {
    fontFamily: "'Sora', sans-serif",
    fontSize: 28,
    fontWeight: 700,
    color: "#0F172A",
    marginBottom: 6,
  },
  formSubtitle: {
    fontSize: 15,
    color: "#64748B",
  },
  errorBox: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "#FEF2F2",
    border: "1px solid #FECACA",
    borderRadius: 10,
    padding: "12px 16px",
    marginBottom: 24,
    fontSize: 14,
    color: "#DC2626",
    fontWeight: 500,
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  label: {
    fontSize: 13,
    fontWeight: 600,
    color: "#374151",
  },
  input: {
    width: "100%",
    padding: "12px 14px",
    border: "1.5px solid #E2E8F0",
    borderRadius: 10,
    fontSize: 14,
    fontFamily: "'DM Sans', sans-serif",
    background: "#fff",
    outline: "none",
    transition: "border-color 0.2s",
    color: "#0F172A",
  },
  passwordWrapper: {
    position: "relative",
  },
  showPasswordBtn: {
    position: "absolute",
    right: 12,
    top: "50%",
    transform: "translateY(-50%)",
    background: "none",
    border: "none",
    fontSize: 12,
    color: "#64748B",
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  hint: {
    fontSize: 12,
    color: "#94A3B8",
    margin: 0,
  },
  submitBtn: {
    width: "100%",
    padding: "13px",
    background: "linear-gradient(135deg, #1D4ED8, #0EA5E9)",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    marginTop: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    transition: "opacity 0.2s",
  },
  spinner: {
    width: 16,
    height: 16,
    border: "2px solid rgba(255,255,255,0.3)",
    borderTop: "2px solid #fff",
    borderRadius: "50%",
    animation: "spin 0.7s linear infinite",
  },
  toggleContainer: {
    marginTop: 24,
    textAlign: "center",
    fontSize: 14,
  },
  toggleText: {
    color: "#64748B",
  },
  toggleBtn: {
    background: "none",
    border: "none",
    color: "#1D4ED8",
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 14,
    marginLeft: 6,
  },
};

export default styles;
