const styles = {
  nav: {
    position: "sticky",
    top: 0,
    zIndex: 100,
    background: "#0F172A",
    height: 64,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 32px",
    boxShadow: "0 1px 0 rgba(255,255,255,0.06)",
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    cursor: "pointer",
    userSelect: "none",
  },
  logoIcon: {
    width: 36,
    height: 36,
    background: "linear-gradient(135deg, #1D4ED8, #0EA5E9)",
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  brandText: {
    color: "#fff",
    fontFamily: "'Sora', 'DM Sans', sans-serif",
    fontWeight: 700,
    fontSize: 18,
    letterSpacing: "-0.3px",
  },
  links: {
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  navLink: {
    background: "transparent",
    border: "none",
    color: "#94A3B8",
    padding: "8px 16px",
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s",
    fontFamily: "inherit",
  },
  navLinkActive: {
    background: "rgba(29, 78, 216, 0.25)",
    color: "#60A5FA",
  },
  right: {
    display: "flex",
    alignItems: "center",
    gap: 16,
  },
  userInfo: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    background: "linear-gradient(135deg, #1D4ED8, #0EA5E9)",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 700,
  },
  userName: {
    color: "#CBD5E1",
    fontSize: 14,
    fontWeight: 500,
  },
  logoutBtn: {
    background: "rgba(239,68,68,0.12)",
    border: "1px solid rgba(239,68,68,0.25)",
    color: "#F87171",
    padding: "7px 16px",
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.15s",
  },
};
export default styles;
