const styles = {
  page: {
    minHeight: "100vh",
    background: "#F0F4F8",
    fontFamily: "'DM Sans', sans-serif",
  },
  main: {
    maxWidth: 900,
    margin: "0 auto",
    padding: "32px 24px 60px",
  },
  loadingCenter: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 300,
    gap: 16,
  },
  spinner: {
    width: 36,
    height: 36,
    border: "3px solid #E2E8F0",
    borderTop: "3px solid #1D4ED8",
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },
  loadingText: { fontSize: 14, color: "#64748B", margin: 0 },
  errorState: {
    textAlign: "center",
    padding: "60px 20px",
  },
  errorIcon: { fontSize: 48, marginBottom: 12 },
  errorTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: "#0F172A",
    marginBottom: 16,
    fontFamily: "'Sora', sans-serif",
  },
  backBtn: {
    background: "#1D4ED8",
    color: "#fff",
    border: "none",
    padding: "10px 22px",
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  back: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    color: "#475569",
    background: "none",
    border: "none",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    marginBottom: 24,
    fontFamily: "inherit",
    padding: 0,
  },
  pageHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
    flexWrap: "wrap",
    gap: 12,
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: 16,
  },
  reportIcon: {
    width: 54,
    height: 54,
    background: "#fff",
    border: "1px solid #E2E8F0",
    borderRadius: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 26,
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
  },
  reportName: {
    fontFamily: "'Sora', sans-serif",
    fontSize: 22,
    fontWeight: 700,
    color: "#0F172A",
    marginBottom: 4,
  },
  reportType: {
    fontSize: 14,
    color: "#64748B",
    margin: 0,
  },
  statusBadge: {
    padding: "7px 16px",
    borderRadius: 20,
    fontSize: 13,
    fontWeight: 700,
    display: "inline-block",
  },
  stepper: {
    display: "flex",
    alignItems: "center",
    background: "#fff",
    borderRadius: 14,
    padding: "20px 28px",
    marginBottom: 20,
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
  },
  stepItem: {
    display: "flex",
    alignItems: "center",
    flex: 1,
    position: "relative",
  },
  stepCircle: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    borderWidth: "2px",
    borderStyle: "solid",
    borderColor: "#E2E8F0",
    background: "#F8FAFC",
    color: "#94A3B8",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 700,
    flexShrink: 0,
    zIndex: 1,
  },
  stepLabel: {
    marginLeft: 10,
    flex: 1,
  },
  stepName: {
    fontSize: 13,
    fontWeight: 500,
    color: "#64748B",
  },
  stepLine: {
    flex: 1,
    height: 2,
    margin: "0 8px",
    borderRadius: 2,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "1fr 1.1fr",
    gap: 18,
  },
  card: {
    background: "#fff",
    borderRadius: 16,
    padding: "26px 28px",
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
  },
  cardTitle: {
    fontFamily: "'Sora', sans-serif",
    fontSize: 16,
    fontWeight: 700,
    color: "#0F172A",
    marginBottom: 20,
    paddingBottom: 14,
    borderBottom: "1px solid #F1F5F9",
  },
  metaList: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  metaRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
  },
  metaKey: {
    fontSize: 13,
    color: "#94A3B8",
    fontWeight: 500,
    flexShrink: 0,
  },
  metaVal: {
    fontSize: 13,
    color: "#1E293B",
    fontWeight: 500,
    textAlign: "right",
    wordBreak: "break-all",
  },
  actionArea: {
    marginTop: 24,
    paddingTop: 20,
    borderTop: "1px solid #F1F5F9",
  },
  actionLabel: {
    fontSize: 12,
    color: "#94A3B8",
    marginBottom: 10,
    fontWeight: 500,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  actionBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    width: "100%",
    padding: "11px",
    background: "linear-gradient(135deg, #1D4ED8, #0EA5E9)",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "opacity 0.2s",
  },
  btnLoader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  spinnerSmall: {
    display: "inline-block",
    width: 13,
    height: 13,
    border: "2px solid rgba(255,255,255,0.35)",
    borderTop: "2px solid #fff",
    borderRadius: "50%",
    animation: "spin 0.7s linear infinite",
  },
  summaryBox: {
    background: "#F0FDF4",
    border: "1px solid #A7F3D0",
    borderRadius: 12,
    padding: "18px 20px",
  },
  summaryHeader: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    marginBottom: 12,
  },
  summaryReady: {
    fontSize: 13,
    fontWeight: 700,
    color: "#059669",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  summaryText: {
    fontSize: 14,
    color: "#1E293B",
    lineHeight: 1.75,
    margin: 0,
  },
  pendingBox: {
    textAlign: "center",
    padding: "32px 16px",
  },
  pendingIcon: {
    fontSize: 40,
    marginBottom: 12,
  },
  pendingTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: "#374151",
    marginBottom: 8,
    fontFamily: "'Sora', sans-serif",
  },
  pendingDesc: {
    fontSize: 13,
    color: "#94A3B8",
    lineHeight: 1.6,
    margin: 0,
  },
  processingAnim: {
    display: "flex",
    justifyContent: "center",
    gap: 6,
    marginBottom: 16,
  },
  processingDot: {
    width: 10,
    height: 10,
    background: "#F59E0B",
    borderRadius: "50%",
    animation: "bounce 1s ease-in-out infinite",
  },
};
export default styles;
