const styles = {
  page: {
    minHeight: "100vh",
    background: "#F0F4F8",
    fontFamily: "'DM Sans', sans-serif",
  },
  main: {
    maxWidth: 680,
    margin: "0 auto",
    padding: "32px 24px 60px",
  },
  back: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    color: "#475569",
    background: "none",
    border: "none",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    marginBottom: 24,
    fontFamily: "inherit",
    padding: 0,
    transition: "color 0.15s",
  },
  card: {
    background: "#fff",
    borderRadius: 18,
    padding: "32px 36px",
    boxShadow: "0 2px 12px rgba(0,0,0,0.07)",
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    marginBottom: 28,
    paddingBottom: 24,
    borderBottom: "1px solid #F1F5F9",
  },
  headerIcon: {
    width: 50,
    height: 50,
    background: "#EFF6FF",
    borderRadius: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  cardTitle: {
    fontFamily: "'Sora', sans-serif",
    fontSize: 20,
    fontWeight: 700,
    color: "#0F172A",
    marginBottom: 4,
  },
  cardSub: {
    fontSize: 14,
    color: "#64748B",
    margin: 0,
  },
  errorBox: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "#FEF2F2",
    border: "1px solid #FECACA",
    borderRadius: 10,
    padding: "12px 14px",
    marginBottom: 20,
    fontSize: 14,
    color: "#DC2626",
    fontWeight: 500,
  },
  form: { display: "flex", flexDirection: "column", gap: 22 },
  twoCol: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 16,
  },
  field: { display: "flex", flexDirection: "column", gap: 7 },
  label: {
    fontSize: 13,
    fontWeight: 600,
    color: "#374151",
  },
  required: { color: "#EF4444" },
  input: {
    padding: "11px 14px",
    border: "1.5px solid #E2E8F0",
    borderRadius: 10,
    fontSize: 14,
    fontFamily: "'DM Sans', sans-serif",
    background: "#F8FAFC",
    outline: "none",
    transition: "border-color 0.2s",
    color: "#0F172A",
    width: "100%",
    boxSizing: "border-box",
  },
  select: {
    padding: "11px 14px",
    border: "1.5px solid #E2E8F0",
    borderRadius: 10,
    fontSize: 14,
    fontFamily: "'DM Sans', sans-serif",
    background: "#F8FAFC",
    outline: "none",
    transition: "border-color 0.2s",
    color: "#0F172A",
    width: "100%",
    cursor: "pointer",
  },
  dropZone: {
    border: "2px dashed #CBD5E1",
    borderRadius: 14,
    padding: "36px 24px",
    textAlign: "center",
    cursor: "pointer",
    background: "#F8FAFC",
    transition: "all 0.15s",
  },
  dropZoneActive: {
    borderColor: "#1D4ED8",
    background: "#EFF6FF",
  },
  dropZoneHasFile: {
    borderColor: "#10B981",
    background: "#F0FDF4",
    borderStyle: "solid",
  },
  dropContent: {},
  dropIconWrap: {
    width: 56,
    height: 56,
    background: "#E2E8F0",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 12px",
  },
  dropTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: "#374151",
    margin: "0 0 4px",
  },
  dropSub: {
    fontSize: 14,
    color: "#94A3B8",
    margin: "0 0 8px",
  },
  browseLink: {
    color: "#1D4ED8",
    fontWeight: 600,
  },
  dropHint: {
    fontSize: 12,
    color: "#CBD5E1",
    margin: 0,
  },
  fileInfo: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    justifyContent: "center",
  },
  fileIcon: { fontSize: 32 },
  fileName: {
    margin: "0 0 2px",
    fontSize: 14,
    fontWeight: 600,
    color: "#0F172A",
    textAlign: "left",
  },
  fileSize: {
    margin: 0,
    fontSize: 12,
    color: "#64748B",
    textAlign: "left",
  },
  removeFile: {
    background: "#FEF2F2",
    border: "1px solid #FECACA",
    color: "#EF4444",
    width: 28,
    height: 28,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 700,
    marginLeft: "auto",
  },
  actions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 12,
    paddingTop: 4,
  },
  cancelBtn: {
    padding: "11px 22px",
    background: "#fff",
    border: "1.5px solid #E2E8F0",
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    color: "#475569",
    fontFamily: "inherit",
  },
  submitBtn: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "11px 24px",
    background: "linear-gradient(135deg, #1D4ED8, #0EA5E9)",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "opacity 0.2s",
    boxShadow: "0 4px 12px rgba(29,78,216,0.25)",
  },
  btnLoader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  spinner: {
    display: "inline-block",
    width: 14,
    height: 14,
    border: "2px solid rgba(255,255,255,0.35)",
    borderTop: "2px solid #fff",
    borderRadius: "50%",
    animation: "spin 0.7s linear infinite",
  },
  infoNote: {
    marginTop: 20,
    padding: "14px 18px",
    background: "#F0F9FF",
    border: "1px solid #BAE6FD",
    borderRadius: 10,
    fontSize: 13,
    color: "#0369A1",
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    lineHeight: 1.5,
  },
};
export default styles;
